"""empty message

Revision ID: 522174159773
Revises: 
Create Date: 2019-02-16 15:12:05.287043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '522174159773'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club', sa.Column('abbreviation', sa.String(length=255), nullable=True))
    op.add_column('club', sa.Column('logo', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'club', ['logo'])
    op.create_unique_constraint(None, 'club', ['abbreviation'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'club', type_='unique')
    op.drop_constraint(None, 'club', type_='unique')
    op.drop_column('club', 'logo')
    op.drop_column('club', 'abbreviation')
    # ### end Alembic commands ###
